#!/usr/bin/env bash
#display user id home path
# Read /etc/passwd line by line
while IFS=: read -r username _ user_id _ _ home_dir _
do
  # Print the formatted output using printf for better portability
  printf "%s:%s:%s\n" "${username}" "${user_id}" "${home_dir}"
done < /etc/passwd

