#!/usr/bin/env bash
#display good and bad luck
count=1
while [ "$count" -le 10 ]; do
    if [ "$count" -eq 4 ]; then
        echo "bad luck"
    elseif [ "$count" -eq 8 ]; then
        echo "good luck"
    else 
        echo "Best School"
    fi
    count=$((count + 1))
done
