#!/usr/bin/env bash
#checks if file exists and many more
FILE="school"
if [ -e "$FILE" ]; then
 echo "File exists"
 if [ ! -s "$FILE" ]; then
   echo "File is empty"
 else
   echo "File is not empty"
 fi
 if [ -f "$FILE" ]; then
   echo "$FILE is a regular file"
 fi
else 
 echo "File does not exist"
fi

