#!/usr/bin/env bash
# Write a Bash script that runs pid and encounter signals
kill_p() {
    rm /var/run/myscript.pid
    exit 0
}

trap "echo 'I hate the kill command' && kill_p" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "kill_p" SIGQUIT
echo '$$' > /var/run/myscript.pid
while true
do
  echo "To infinity and beyond"
  sleep 2
done
