#!/usr/bin/env bash
#Bash (init) script that manages manage_my_process
kill_p() {
    kill "$(pgrep -f /manage_my_process)"
    rm -f /var/run/my_process.pid &
}

if [[ "$1" == "start" ]]
then
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
elif [[ "$1" == "stop" ]]
then
    kill_p; echo "manage_my_process stopped";
elif [[ "$1" == "restart" ]]
then
    kill_p; ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
